server:
  port: 8080
  servlet:
    context-path: /article

spring:
  datasource:
    url: "jdbc:mysql://root:rJvbfAdAUSKUUfbUNNgegOvFOeWPdqPp@mysql.railway.internal:3306/railway"
    username: root
    password: rJvbfAdAUSKUUfbUNNgegOvFOeWPdqPp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

jwt:
    signerKey: KMPH22iU4IExFBhtdQhyZoCn2JRkZ/WJeuu26VMZsH5SXXCfOxAVQwDwrDxHov1o

cloudinary:
  cloud-name: dndsrbf9s
  api-key: 932944391659178
  api-secret: _UlDjHd_T5WxNV0iZMMN9tGJuy0
  secure: true
